# Generated by Django 4.1.3 on 2022-11-06 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shares_data_source', models.CharField(max_length=64)),
                ('crypto_data_source', models.CharField(max_length=64)),
                ('default_currency', models.CharField(max_length=64)),
                ('default_shares_exchange', models.CharField(max_length=64)),
                ('default_shares_platform', models.CharField(max_length=64)),
                ('default_crypto_exchange', models.CharField(max_length=64)),
                ('default_crypto_platform', models.CharField(max_length=64)),
            ],
        ),
    ]
