# Generated by Django 4.1.3 on 2022-11-06 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Financials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('key', models.CharField(default=None, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(default=None, max_length=32, null=True)),
                ('symbol', models.CharField(default=None, max_length=32, null=True)),
                ('type', models.CharField(choices=[('Shares', 'Shares'), ('Crypto', 'Crypto')], default='Shares', max_length=16)),
                ('live_price', models.FloatField(default=0)),
                ('price_history', models.JSONField(null=True)),
                ('value_history', models.JSONField(null=True)),
                ('plot_path', models.CharField(default='./', max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.FloatField()),
                ('price_per_unit', models.FloatField()),
                ('fee', models.FloatField()),
                ('date', models.DateField(auto_now=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.investment')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5)),
                ('investment_type', models.CharField(choices=[('Shares', 'Shares'), ('Crypto', 'Crypto')], default='Shares', max_length=16)),
                ('investment_name', models.CharField(default='unnamed', max_length=128)),
                ('currency', models.CharField(default='AUD', max_length=5)),
                ('exchange', models.CharField(choices=[('XAMS', 'XAMS'), ('XASX', 'XASX'), ('XBOM', 'XBOM'), ('XBRU', 'XBRU'), ('XFRA', 'XFRA'), ('XHKG', 'XHKG'), ('XJPX', 'XJPX'), ('XKOS', 'XKOS'), ('XLIS', 'XLIS'), ('XLON', 'XLON'), ('XMIL', 'XMIL'), ('XMSM', 'XMSM'), ('XNAS', 'XNAS'), ('XNSE', 'XNSE'), ('XNYS', 'XNYS'), ('XOSL', 'XOSL'), ('XSAU', 'XSAU'), ('XSHE', 'XSHE'), ('XSHG', 'XSHG'), ('XSWX', 'XSWX'), ('XTAI', 'XTAI'), ('XTSE', 'XTSE')], default='XASX', max_length=4)),
                ('platform', models.CharField(choices=[('CMC', 'CMC'), ('LINK', 'LINK'), ('BOARDROOM', 'BOARDROOM'), ('DIRECT', 'DIRECT'), ('IPO', 'IPO')], default='CMC', max_length=128)),
                ('units', models.FloatField()),
                ('price_per_unit', models.FloatField()),
                ('fee', models.FloatField()),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.investment')),
            ],
            options={
                'unique_together': {('exchange', 'symbol', 'date_time')},
            },
        ),
    ]
