# Generated by Django 5.1.1 on 2024-10-05 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Financials",
        ),
    ]
