# Generated by Django 4.2.6 on 2023-10-10 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='history',
            unique_together={('user', 'investment', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='investment',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('user', 'investment', 'date_time')},
        ),
        migrations.AlterUniqueTogether(
            name='sale',
            unique_together={('user', 'investment', 'date_time')},
        ),
        migrations.RemoveField(
            model_name='history',
            name='open',
        ),
    ]
