# Generated by Django 4.2.5 on 2023-10-01 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_investment_sale_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='fee',
            new_name='fees',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 1, 4, 54, 14, 164150)),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 10, 1, 4, 54, 14, 164540)),
        ),
    ]
