# Generated by Django 5.1.1 on 2024-09-27 04:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_purchase_date_alter_sale_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financials',
            old_name='bank_balance',
            new_name='total_earned_on_sale',
        ),
        migrations.RenameField(
            model_name='financials',
            old_name='total_earned',
            new_name='total_spent_on_purcase',
        ),
        migrations.RenameField(
            model_name='financials',
            old_name='total_spent',
            new_name='total_value',
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('high', models.FloatField(default=0)),
                ('low', models.FloatField(default=0)),
                ('close', models.FloatField(default=0)),
                ('volume', models.IntegerField(default=0)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.investment')),
            ],
        ),
    ]
