# Generated by Django 4.2.6 on 2023-10-11 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_history_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='investment',
            name='symbol',
            field=models.CharField(max_length=8),
        ),
    ]
