# Generated by Django 4.2.5 on 2023-10-01 04:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_fee_purchase_fees_alter_purchase_date_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
