# Generated by Django 5.1.1 on 2024-09-27 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_bank_balance_financials_total_earned_on_sale_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='DividendPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('value', models.FloatField()),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.investment')),
            ],
        ),
        migrations.CreateModel(
            name='DividendReinvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cutoff_date', models.DateField()),
                ('reinvestment_date', models.DateField()),
                ('cutoff_date_value', models.FloatField()),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.investment')),
            ],
        ),
    ]
