# Generated by Django 5.1.1 on 2024-09-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_history_date_dividendpayment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dividendreinvestment',
            name='cutoff_date_value',
        ),
        migrations.AddField(
            model_name='dividendreinvestment',
            name='units',
            field=models.IntegerField(default=0),
        ),
    ]
