# Generated by Django 5.1.1 on 2024-12-14 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_purchase_exchange_alter_purchase_platform_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="investment",
            name="plot_path",
        ),
        migrations.AlterField(
            model_name="purchase",
            name="exchange",
            field=models.CharField(
                choices=[
                    ("XASX", "ASX"),
                    ("XAMS", "AMS"),
                    ("XBOM", "BOM"),
                    ("XBRU", "BRU"),
                    ("XFRA", "FRA"),
                    ("XHKG", "HKG"),
                    ("XJPX", "JPX"),
                    ("XKOS", "KOS"),
                    ("XLIS", "LIS"),
                    ("XLON", "LON"),
                    ("XMIL", "MIL"),
                    ("XMSM", "MSM"),
                    ("XNAS", "NAS"),
                    ("XNSE", "NSE"),
                    ("XNYS", "NYS"),
                    ("XOSL", "OSL"),
                    ("XSAU", "SAU"),
                    ("XSHE", "SHE"),
                    ("XSHG", "SHG"),
                    ("XSWX", "SWX"),
                    ("XTAI", "TAI"),
                    ("XTSE", "TSE"),
                ],
                default="XASX",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="platform",
            field=models.CharField(
                choices=[
                    ("CMC", "CMC"),
                    ("LINK", "LINK"),
                    ("BOARDROOM", "BOARDROOM"),
                    ("DIRECT", "DIRECT"),
                    ("IPO", "IPO"),
                ],
                default="CMC",
                max_length=128,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="exchange",
            field=models.CharField(
                choices=[
                    ("XASX", "ASX"),
                    ("XAMS", "AMS"),
                    ("XBOM", "BOM"),
                    ("XBRU", "BRU"),
                    ("XFRA", "FRA"),
                    ("XHKG", "HKG"),
                    ("XJPX", "JPX"),
                    ("XKOS", "KOS"),
                    ("XLIS", "LIS"),
                    ("XLON", "LON"),
                    ("XMIL", "MIL"),
                    ("XMSM", "MSM"),
                    ("XNAS", "NAS"),
                    ("XNSE", "NSE"),
                    ("XNYS", "NYS"),
                    ("XOSL", "OSL"),
                    ("XSAU", "SAU"),
                    ("XSHE", "SHE"),
                    ("XSHG", "SHG"),
                    ("XSWX", "SWX"),
                    ("XTAI", "TAI"),
                    ("XTSE", "TSE"),
                ],
                default="XASX",
                max_length=4,
            ),
        ),
    ]
