# Generated by Django 4.2.5 on 2023-10-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_purchase_date_time_alter_sale_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='fee',
            new_name='fees',
        ),
    ]
