# Generated by Django 5.1.1 on 2024-10-16 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_delete_financials"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(default="")),
                ("daily_change", models.FloatField(default=0)),
                ("daily_change_percent", models.FloatField(default=0)),
            ],
        ),
    ]
