# Generated by Django 5.1.7 on 2025-04-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="investment",
            name="visible",
            field=models.BooleanField(default=True),
        ),
    ]
