# Generated by Django 5.2.1 on 2025-05-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_investment_visible"),
    ]

    operations = [
        migrations.AddField(
            model_name="dividendreinvestment",
            name="price_per_unit",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
