# Generated by Django 5.2.1 on 2025-05-27 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_dividendreinvestment_price_per_unit"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dividendpayment",
            old_name="payment_date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="dividendreinvestment",
            old_name="reinvestment_date",
            new_name="date",
        ),
        migrations.AlterUniqueTogether(
            name="dividendpayment",
            unique_together={("date", "investment")},
        ),
        migrations.AlterUniqueTogether(
            name="dividendreinvestment",
            unique_together={("date", "investment")},
        ),
    ]
