# Generated by Django 4.1.3 on 2022-11-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='adjustedClose',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='close',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='high',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='low',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='open',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='history',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
