version: "3.9"

services:
  db:
    image: postgres:17
    container_name: buffetiser_db
    restart: always
    environment:
      POSTGRES_USER: buffetiser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: BUFFETISER_DB
    volumes:
      - ./postgres_backup:/var/lib/postgresql/backup
    networks:
      - network

  redis:
    image: redis:7-alpine
    container_name: buffetiser_redis
    restart: always
    networks:
      - network

  backend:
    build:
      context: ./backend
    container_name: buffetiser_backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgres://buffetiser:password@db:5433/BUFFETISER_DB
      - REDIS_URL=redis://redis:6379
      - DJANGO_SETTINGS_MODULE=backend.settings.production  # 👈 Important for Django prod settings
    networks:
      - network

  frontend:
    build:
      context: ./frontend
    container_name: buffetiser_frontend
    command: ["sh", "-c", "npm install && npm run build"]
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - network

  nginx:
    image: nginx:alpine
    container_name: buffetiser_nginx
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
      - ./certs:/etc/ssl/certs:ro
    ports:
      - "81:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    networks:
      - network

networks:
  network:
    driver: bridge
