name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v5
        with:
          context: ../buffetiser/backend
          push: true
          tags: dodgydesigns/buffetiser-backend:latest
          platforms: linux/amd64

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: ../buffetiser/frontend
          push: true
          tags: dodgydesigns/buffetiser-frontend:latest
          platforms: linux/amd64
